### ISSUE TITLE
Certificate Issue?

### ISSUE THREAD

**Issue by Camawama** [way2muchnoise/CurseForgeBadge#47] opened 2024-04-24 01:58 UTC
Unsure what this is about but Bitdefender kept alerting me when I opened chrome. I looked it up and this GitHub is the first thing I found.
![image](https://github.com/way2muchnoise/CurseForgeBadge-Unofficial/assets/43620900/512667ad-e298-44ea-97ac-68ef8ec4ebd7)

**Comment by way2muchnoise** [comment] 2024-04-24 16:01
Duplicate of #46, I renewed my cert just a little to late. Fixed now

**Closed as completed by way2muchnoise** 2024-04-24 16:01 UTC
